name: Deploy Weather App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Lambda and Frontend
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Debug AWS region env variables (optional)
        run: |
          echo "AWS_REGION: $AWS_REGION"
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
          echo "GitHub secret AWS_REGION: ${{ secrets.AWS_REGION }}"

      - name: Deploy Lambda function
        run: |
          cd lambda
          zip function.zip weather.py
          aws lambda update-
